# Generated by Django 5.1.3 on 2024-11-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasfunciones',
                                               to='access.function')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasfunciones',
                                           to='access.role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='functions',
            field=models.ManyToManyField(through='access.RoleFunction', to='access.function'),
        ),
        migrations.AddField(
            model_name='function',
            name='roles',
            field=models.ManyToManyField(through='access.RoleFunction', to='access.role'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losroles',
                                           to='access.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losroles',
                                           to='access.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='access.UserRole', to='access.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='access.UserRole', to='access.user'),
        ),
    ]
