# Generated by Django 5.1.3 on 2024-11-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
