# Generated by Django 5.1.3 on 2024-11-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
