# Generated by Django 5.1.3 on 2024-11-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
